# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def cowinapp_inhouse_pods
  
  #Development Pods
    pod 'CWNetworkSDK', :path => "SDKS/"
    pod 'HelperKit', :git => 'https://github.com/MobileUtils/HelperKit-iOS'
    
end

def cowinapp_thirdparty_pods
    pod 'Hero'
    pod 'CHIPageControl'
end

target 'Cowin' do
  use_frameworks!
  cowinapp_inhouse_pods
  cowinapp_thirdparty_pods
end

